### ISSUE TITLE
CreateIndividual does not work anymore

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Matlab-Toolbox-Core#15]
```
Error using PKSimCreateIndividual (line 219)
System.TypeInitializationException: The type initializer for 'PKSim.Matlab.MatlabIndividualFactory' threw an exception. --->
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0,
Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. Das System kann die angegebene Datei nicht finden.

   at PKSim.Infrastructure.InfrastructureRegister.registerLogging(IContainer container)

   at PKSim.Infrastructure.InfrastructureRegister.Initialize()

   at PKSim.Matlab.ApplicationStartup.initializeForMatlab()

   at PKSim.Matlab.ApplicationStartup.Initialize()

   at PKSim.Matlab.MatlabIndividualFactory..cctor()

   --- End of inner exception stack trace ---

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)

   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo
   culture)

   at dotnetcli.NETConstructor.invoke(NETConstructor* , COSClient* client, Int32* nlhs, COSValue* plhs, Int32 nrhs, COSValue* prhs)

```

**Comment by msevestre** [comment]
What's the issue??

**Comment by Yuri05** [comment]
when calling PKSimMatlab from Matlab:
```
Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.0.1.0,
Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies.
```

**Comment by Yuri05** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/1015
